---
title: "Projet final - Kim Thifault et Laurie Labonté"
date: "16 décembre 2024"
output: github_document
---

```{r}
#| label: setup
#| include: false

knitr::opts_chunk$set(echo = FALSE)
```

```{r}
#| label: load-packages
#| message: false
 
library(tidyverse)

```

```{r}
#| label: load-data
#| message: false

hate_crime <- read_csv("data/hate_crime.csv")
Crime_NY <- read_csv("data/final_data.csv")
Crime_LA <- read_csv("data/crimes_all_cleaned.csv")

```
## Introduction

## Données

## Analyse des données

#### Première étape:

Tout d'abord, 

```{r}
crime <- hate_crime %>%
  select(DATA_YEAR, STATE_ABBR) %>%
  filter(DATA_YEAR >= "2010")
crime

```

Maintenant, 

```{r}
top10 <- crime %>%
  group_by(STATE_ABBR) %>%
  count(STATE_ABBR, sort = TRUE) %>%
  head(n = 10)
knitr::kable(top10)


ggplot(top10, aes(x = STATE_ABBR, y = n, fill = n)) + geom_col()  + labs(x = "États", y = "Nombre d'actes criminels", title = "Les 10 États les plus criminalisées des États-Unis", subtitle = "Depuis 2010")

```

Comme nous pouvons le constater, l'état de la Californie et de New York ont tous deux le taux de crime le plus élevé des États-Unis depuis 2010


Sélection des crimes entre 2010 et 2019 dans chacune des bases de données
```{r}

crime_ny <- Crime_NY %>%
  filter(year >= "2010", year <= "2019")
crime_ny

crime_la <- Crime_LA %>%
  filter(occured_date >= "2010-01-01", occured_date <= "2020-01-01")
crime_la

```


```{r}

area <- crime_ny %>%
  count(BORO_NM, sort = TRUE)
knitr::kable(area)

ggplot(area, aes(x = BORO_NM, y = n)) + geom_col()

```